### ISSUE TITLE
No data from Kamstrup meter

### ISSUE THREAD

**Issue by Chrisiesmit93** [golles/ha-kamstrup_403#16]
### Did you read the instructions?

- [X] I have read the [README](../blob/main/README.md), including the [known-limitations](../blob/main/README.md#known-limitations) section.

### The problem

I don't get any data anymore from my Kamstrup meter the last few days/week.
(don't know when this problem occured and also removed the history when I re-added the integration)

I tried to "wake up" the meter by pressing 1 of the 2 buttons (worked sometime before with an different approach than this integration), but this didn't help solve the problem (the meter display itself is working, so no empty batteries I think)

In my HA logs I got the following error every time it gets data:
```
2022-06-29 12:17:32 ERROR (MainThread) [custom_components.kamstrup_403] Unexpected error fetching kamstrup_403 data: bytearray index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kamstrup_403/__init__.py", line 89, in _async_update_data
    value, unit = self.kamstrup.readvar(SENSORS[key]["command"])
  File "/config/custom_components/kamstrup_403/kamstrup.py", line 200, in readvar
    if b[0] != 0x3F or b[1] != 0x10:
IndexError: bytearray index out of range
```

I just raised the log level to debug and now I get this message after HA startup:
```
2022-06-29 12:27:14 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kamstrup_403 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-29 12:27:24 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:27:25 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.201 seconds (success: True)
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] async_setup_entry
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Heat Energy (E1)
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Power
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Temp1
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Temp2
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Tempdiff
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Flow
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Volume
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Temp1xm3
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Temp2xm3
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Infoevent
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor HourCounter
```

And this messages every minute after HA startup:
```
2022-06-29 12:28:29 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:28:32 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.109 seconds (success: True)
```

### What version of this integration has the issue?

1.2.0

### What version of Home Assistant Core has the issue?

Core 2022.6.7

### Home Assistant log

```shell
2022-06-29 12:27:14 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kamstrup_403 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-29 12:27:24 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:27:25 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.201 seconds (success: True)
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] async_setup_entry
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Heat Energy (E1)
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Power
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Temp1
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Temp2
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Tempdiff
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Flow
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Volume
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Temp1xm3
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Temp2xm3
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor Infoevent
2022-06-29 12:27:29 DEBUG (MainThread) [custom_components.kamstrup_403] add sensor HourCounter
2022-06-29 12:28:29 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:28:32 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.109 seconds (success: True)
2022-06-29 12:29:32 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:29:33 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.152 seconds (success: True)
2022-06-29 12:30:33 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:30:36 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.182 seconds (success: True)
2022-06-29 12:31:36 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:31:39 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.103 seconds (success: True)
2022-06-29 12:32:39 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:32:40 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.162 seconds (success: True)
2022-06-29 12:33:40 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:33:41 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.139 seconds (success: True)
2022-06-29 12:34:41 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:34:44 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.177 seconds (success: True)
2022-06-29 12:35:44 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:35:47 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.179 seconds (success: True)
2022-06-29 12:36:47 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:36:50 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.204 seconds (success: True)
2022-06-29 12:37:50 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:37:53 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.098 seconds (success: True)
2022-06-29 12:38:53 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:38:54 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.184 seconds (success: True)
2022-06-29 12:39:54 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:39:57 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.112 seconds (success: True)
2022-06-29 12:40:57 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:40:58 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.157 seconds (success: True)
2022-06-29 12:41:58 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:41:59 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.143 seconds (success: True)
2022-06-29 12:42:59 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:43:02 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.176 seconds (success: True)
2022-06-29 12:44:02 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:44:05 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.123 seconds (success: True)
2022-06-29 12:45:05 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:45:06 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.180 seconds (success: True)
2022-06-29 12:46:06 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:46:09 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.118 seconds (success: True)
2022-06-29 12:47:09 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:47:10 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.176 seconds (success: True)
2022-06-29 12:48:10 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:48:13 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.122 seconds (success: True)
2022-06-29 12:49:13 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:49:14 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.166 seconds (success: True)
2022-06-29 12:50:14 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:50:19 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 5.116 seconds (success: True)
2022-06-29 12:51:19 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:51:20 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.180 seconds (success: True)
2022-06-29 12:52:20 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:52:25 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 5.101 seconds (success: True)
2022-06-29 12:53:25 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:53:26 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.139 seconds (success: True)
2022-06-29 12:54:26 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:54:29 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.176 seconds (success: True)
2022-06-29 12:55:29 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:55:32 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.151 seconds (success: True)
2022-06-29 12:56:32 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:56:35 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.176 seconds (success: True)
2022-06-29 12:57:35 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:57:38 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.101 seconds (success: True)
2022-06-29 12:58:38 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:58:41 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.175 seconds (success: True)
2022-06-29 12:59:41 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 12:59:44 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.171 seconds (success: True)
2022-06-29 13:00:44 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:00:47 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.185 seconds (success: True)
2022-06-29 13:01:47 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:01:50 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.110 seconds (success: True)
2022-06-29 13:02:50 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:02:53 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.157 seconds (success: True)
2022-06-29 13:03:53 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:03:54 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.146 seconds (success: True)
2022-06-29 13:04:54 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:04:55 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.153 seconds (success: True)
2022-06-29 13:05:55 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:05:58 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.175 seconds (success: True)
2022-06-29 13:06:58 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:07:01 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.121 seconds (success: True)
2022-06-29 13:08:01 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:08:04 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.181 seconds (success: True)
2022-06-29 13:09:04 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:09:07 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.130 seconds (success: True)
2022-06-29 13:10:07 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:10:10 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.164 seconds (success: True)
2022-06-29 13:11:10 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:11:11 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.175 seconds (success: True)
2022-06-29 13:12:11 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:12:14 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.122 seconds (success: True)
2022-06-29 13:13:14 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:13:15 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.163 seconds (success: True)
2022-06-29 13:14:15 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:14:18 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.126 seconds (success: True)
2022-06-29 13:15:18 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:15:19 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.146 seconds (success: True)
2022-06-29 13:16:19 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:16:20 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.162 seconds (success: True)
2022-06-29 13:17:20 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:17:23 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.173 seconds (success: True)
2022-06-29 13:18:23 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:18:26 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.114 seconds (success: True)
2022-06-29 13:19:26 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:19:27 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.183 seconds (success: True)
2022-06-29 13:20:27 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:20:30 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.111 seconds (success: True)
2022-06-29 13:21:30 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:21:33 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.169 seconds (success: True)
2022-06-29 13:22:33 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:22:36 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.170 seconds (success: True)
2022-06-29 13:23:36 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:23:41 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 5.123 seconds (success: True)
2022-06-29 13:24:41 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:24:42 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.166 seconds (success: True)
2022-06-29 13:25:42 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:25:47 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 5.119 seconds (success: True)
2022-06-29 13:26:47 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:26:48 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 1.178 seconds (success: True)
2022-06-29 13:27:48 DEBUG (MainThread) [custom_components.kamstrup_403] KamstrupUpdateCoordinator: _async_update_data start
2022-06-29 13:27:51 DEBUG (MainThread) [custom_components.kamstrup_403] Finished fetching kamstrup_403 data in 3.112 seconds (success: True)
```

**Comment by golles** [comment]
Hi @Chrisiesmit93 

It looks like, that after you restarted (to enable logging), everything runs fine, can you confirm that?

I'm not entirely sure why that crash happened, somehow the data seemed not to be complete. The only thing I can advise, for now, is to make sure that the reading head is placed correctly on the meter, if it isn't placed correctly it might cause reading errors.

**Comment by golles** [comment]
You might want to give branch #17 a try, this has improved error logging

**Comment by golles** [comment]
#17 is now merged, you could give version `1.2.1` a try

**Comment by Chrisiesmit93** [comment]
Thanks for adding additional logging to this component.
I tested this component and also with another Kamstrup python code, but it seems like that after ~1 year my IR head is not aligned right anymore.
If I hold the IR head in my hand and align it with the meter, I sometimes get the expected data.

I am now 3d printing a case for my IR head to see if that one works better, will get back on this and let you know if the alignment really was my issue after all.

**Comment by golles** [comment]
That sounds very plausible to be the problem.
I also have a 3d printed holder to make sure the reader stays on there correctly.

I'll close this for now, if you notice something else is causing the problem, feel free to reopen this issue or create a new one.
