### ISSUE TITLE
got an unexpected keyword argument 'suggested_display_precision'

### ISSUE THREAD

**Issue by Jimboer** [golles/ha-kamstrup_403#84]
Hi, I get this error on main branch, on previous version 2.3.0 it working properly.

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.loader
Source: custom_components/kamstrup_403/sensor.py:182
Integration: Kamstrup 403 (documentation, issues)
First occurred: 20:15:57 (1 occurrences)
Last logged: 20:15:57

Unexpected exception importing platform custom_components.kamstrup_403.sensor
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.10/site-packages/homeassistant/loader.py", line 722, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/volume1/@appstore/homeassistant/env/lib/python3.10/site-packages/homeassistant/loader.py", line 739, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/var/packages/python310/target/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/volume1/@appstore/homeassistant/var/config/custom_components/kamstrup_403/sensor.py", line 182, in <module>
    SensorEntityDescription(
TypeError: SensorEntityDescription.__init__() got an unexpected keyword argument 'suggested_display_precision'

**Comment by Jimboer** [comment]
Home Assistant 2022.10.5
Frontend-versie: 20221010.0 - latest

**Comment by golles** [comment]
Home Assistant version 2023.3.0 or newer is required to use the version from the main branch. I assume you use an older version?
If not, please open a new issue and fill out the entire form, https://github.com/golles/ha-kamstrup_403/issues/new?assignees=&labels=bug&template=issue.yaml
